/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R2faRouteImport } from './routes/2fa'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/_agent'
import { Route as AuthenticatedBenefRouteImport } from './routes/_authenticated/_benef'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentCadreResultatRouteImport } from './routes/_authenticated/_agent/cadre-resultat'
import { Route as AuthenticatedAgentDispositifsRouteImport } from './routes/_authenticated/_agent/dispositifs'
import { Route as AuthenticatedAgentFinancementsRouteImport } from './routes/_authenticated/_agent/financements'
import { Route as AuthenticatedAgentImputationRouteImport } from './routes/_authenticated/_agent/imputation'
import { Route as AuthenticatedAgentIndicateursRouteImport } from './routes/_authenticated/_agent/indicateurs'
import { Route as AuthenticatedAgentJeunesRouteImport } from './routes/_authenticated/_agent/jeunes'
import { Route as AuthenticatedAgentPfEspaceRouteImport } from './routes/_authenticated/_agent/pf-espace'
import { Route as AuthenticatedAgentPlansDecaissementRouteImport } from './routes/_authenticated/_agent/plans-decaissement'
import { Route as AuthenticatedAgentProjetsRouteImport } from './routes/_authenticated/_agent/projets'
import { Route as AuthenticatedAgentRapportsRouteImport } from './routes/_authenticated/_agent/rapports'
import { Route as AuthenticatedAgentRecouvrementRouteImport } from './routes/_authenticated/_agent/recouvrement'
import { Route as AuthenticatedAgentRemboursementsRouteImport } from './routes/_authenticated/_agent/remboursements'
import { Route as AuthenticatedAgentSuiviRouteImport } from './routes/_authenticated/_agent/suivi'
import { Route as AuthenticatedAgentTransmissionRouteImport } from './routes/_authenticated/_agent/transmission'
import { Route as AuthenticatedBenefMesPiecesRouteImport } from './routes/_authenticated/_benef/mes-pieces'
import { Route as AuthenticatedBenefMesProjetsRouteImport } from './routes/_authenticated/_benef/mes-projets'
import { Route as AuthenticatedAgentAdminLocalitesRouteImport } from './routes/_authenticated/_agent/admin/localites'
import { Route as AuthenticatedAgentAdminParametresRouteImport } from './routes/_authenticated/_agent/admin/parametres'
import { Route as AuthenticatedAgentAdminPartenairesRouteImport } from './routes/_authenticated/_agent/admin/partenaires'
import { Route as AuthenticatedAgentAdminPersonnelsRouteImport } from './routes/_authenticated/_agent/admin/personnels'
import { Route as AuthenticatedAgentAdminProfilsRouteImport } from './routes/_authenticated/_agent/admin/profils'
import { Route as AuthenticatedAgentAdminReferentielsRouteImport } from './routes/_authenticated/_agent/admin/referentiels'
import { Route as AuthenticatedAgentAdminUnitesRouteImport } from './routes/_authenticated/_agent/admin/unites'
import { Route as AuthenticatedAgentAdminWorkflowsRouteImport } from './routes/_authenticated/_agent/admin/workflows'
import { Route as AuthenticatedAgentDispositifWorkflowWorkflowIdRouteImport } from './routes/_authenticated/_agent/dispositif-workflow/$workflowId'

const R2faRoute = R2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/_agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBenefRoute = AuthenticatedBenefRouteImport.update({
  id: '/_benef',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentCadreResultatRoute =
  AuthenticatedAgentCadreResultatRouteImport.update({
    id: '/cadre-resultat',
    path: '/cadre-resultat',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentDispositifsRoute =
  AuthenticatedAgentDispositifsRouteImport.update({
    id: '/dispositifs',
    path: '/dispositifs',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentFinancementsRoute =
  AuthenticatedAgentFinancementsRouteImport.update({
    id: '/financements',
    path: '/financements',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentImputationRoute =
  AuthenticatedAgentImputationRouteImport.update({
    id: '/imputation',
    path: '/imputation',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentIndicateursRoute =
  AuthenticatedAgentIndicateursRouteImport.update({
    id: '/indicateurs',
    path: '/indicateurs',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentJeunesRoute =
  AuthenticatedAgentJeunesRouteImport.update({
    id: '/jeunes',
    path: '/jeunes',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentPfEspaceRoute =
  AuthenticatedAgentPfEspaceRouteImport.update({
    id: '/pf-espace',
    path: '/pf-espace',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentPlansDecaissementRoute =
  AuthenticatedAgentPlansDecaissementRouteImport.update({
    id: '/plans-decaissement',
    path: '/plans-decaissement',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentProjetsRoute =
  AuthenticatedAgentProjetsRouteImport.update({
    id: '/projets',
    path: '/projets',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentRapportsRoute =
  AuthenticatedAgentRapportsRouteImport.update({
    id: '/rapports',
    path: '/rapports',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentRecouvrementRoute =
  AuthenticatedAgentRecouvrementRouteImport.update({
    id: '/recouvrement',
    path: '/recouvrement',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentRemboursementsRoute =
  AuthenticatedAgentRemboursementsRouteImport.update({
    id: '/remboursements',
    path: '/remboursements',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentSuiviRoute = AuthenticatedAgentSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAgentTransmissionRoute =
  AuthenticatedAgentTransmissionRouteImport.update({
    id: '/transmission',
    path: '/transmission',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedBenefMesPiecesRoute =
  AuthenticatedBenefMesPiecesRouteImport.update({
    id: '/mes-pieces',
    path: '/mes-pieces',
    getParentRoute: () => AuthenticatedBenefRoute,
  } as any)
const AuthenticatedBenefMesProjetsRoute =
  AuthenticatedBenefMesProjetsRouteImport.update({
    id: '/mes-projets',
    path: '/mes-projets',
    getParentRoute: () => AuthenticatedBenefRoute,
  } as any)
const AuthenticatedAgentAdminLocalitesRoute =
  AuthenticatedAgentAdminLocalitesRouteImport.update({
    id: '/admin/localites',
    path: '/admin/localites',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminParametresRoute =
  AuthenticatedAgentAdminParametresRouteImport.update({
    id: '/admin/parametres',
    path: '/admin/parametres',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminPartenairesRoute =
  AuthenticatedAgentAdminPartenairesRouteImport.update({
    id: '/admin/partenaires',
    path: '/admin/partenaires',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminPersonnelsRoute =
  AuthenticatedAgentAdminPersonnelsRouteImport.update({
    id: '/admin/personnels',
    path: '/admin/personnels',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminProfilsRoute =
  AuthenticatedAgentAdminProfilsRouteImport.update({
    id: '/admin/profils',
    path: '/admin/profils',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminReferentielsRoute =
  AuthenticatedAgentAdminReferentielsRouteImport.update({
    id: '/admin/referentiels',
    path: '/admin/referentiels',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminUnitesRoute =
  AuthenticatedAgentAdminUnitesRouteImport.update({
    id: '/admin/unites',
    path: '/admin/unites',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentAdminWorkflowsRoute =
  AuthenticatedAgentAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentDispositifWorkflowWorkflowIdRoute =
  AuthenticatedAgentDispositifWorkflowWorkflowIdRouteImport.update({
    id: '/dispositif-workflow/$workflowId',
    path: '/dispositif-workflow/$workflowId',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/2fa': typeof R2faRoute
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cadre-resultat': typeof AuthenticatedAgentCadreResultatRoute
  '/dispositifs': typeof AuthenticatedAgentDispositifsRoute
  '/financements': typeof AuthenticatedAgentFinancementsRoute
  '/imputation': typeof AuthenticatedAgentImputationRoute
  '/indicateurs': typeof AuthenticatedAgentIndicateursRoute
  '/jeunes': typeof AuthenticatedAgentJeunesRoute
  '/pf-espace': typeof AuthenticatedAgentPfEspaceRoute
  '/plans-decaissement': typeof AuthenticatedAgentPlansDecaissementRoute
  '/projets': typeof AuthenticatedAgentProjetsRoute
  '/rapports': typeof AuthenticatedAgentRapportsRoute
  '/recouvrement': typeof AuthenticatedAgentRecouvrementRoute
  '/remboursements': typeof AuthenticatedAgentRemboursementsRoute
  '/suivi': typeof AuthenticatedAgentSuiviRoute
  '/transmission': typeof AuthenticatedAgentTransmissionRoute
  '/mes-pieces': typeof AuthenticatedBenefMesPiecesRoute
  '/mes-projets': typeof AuthenticatedBenefMesProjetsRoute
  '/admin/localites': typeof AuthenticatedAgentAdminLocalitesRoute
  '/admin/parametres': typeof AuthenticatedAgentAdminParametresRoute
  '/admin/partenaires': typeof AuthenticatedAgentAdminPartenairesRoute
  '/admin/personnels': typeof AuthenticatedAgentAdminPersonnelsRoute
  '/admin/profils': typeof AuthenticatedAgentAdminProfilsRoute
  '/admin/referentiels': typeof AuthenticatedAgentAdminReferentielsRoute
  '/admin/unites': typeof AuthenticatedAgentAdminUnitesRoute
  '/admin/workflows': typeof AuthenticatedAgentAdminWorkflowsRoute
  '/dispositif-workflow/$workflowId': typeof AuthenticatedAgentDispositifWorkflowWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/2fa': typeof R2faRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cadre-resultat': typeof AuthenticatedAgentCadreResultatRoute
  '/dispositifs': typeof AuthenticatedAgentDispositifsRoute
  '/financements': typeof AuthenticatedAgentFinancementsRoute
  '/imputation': typeof AuthenticatedAgentImputationRoute
  '/indicateurs': typeof AuthenticatedAgentIndicateursRoute
  '/jeunes': typeof AuthenticatedAgentJeunesRoute
  '/pf-espace': typeof AuthenticatedAgentPfEspaceRoute
  '/plans-decaissement': typeof AuthenticatedAgentPlansDecaissementRoute
  '/projets': typeof AuthenticatedAgentProjetsRoute
  '/rapports': typeof AuthenticatedAgentRapportsRoute
  '/recouvrement': typeof AuthenticatedAgentRecouvrementRoute
  '/remboursements': typeof AuthenticatedAgentRemboursementsRoute
  '/suivi': typeof AuthenticatedAgentSuiviRoute
  '/transmission': typeof AuthenticatedAgentTransmissionRoute
  '/mes-pieces': typeof AuthenticatedBenefMesPiecesRoute
  '/mes-projets': typeof AuthenticatedBenefMesProjetsRoute
  '/admin/localites': typeof AuthenticatedAgentAdminLocalitesRoute
  '/admin/parametres': typeof AuthenticatedAgentAdminParametresRoute
  '/admin/partenaires': typeof AuthenticatedAgentAdminPartenairesRoute
  '/admin/personnels': typeof AuthenticatedAgentAdminPersonnelsRoute
  '/admin/profils': typeof AuthenticatedAgentAdminProfilsRoute
  '/admin/referentiels': typeof AuthenticatedAgentAdminReferentielsRoute
  '/admin/unites': typeof AuthenticatedAgentAdminUnitesRoute
  '/admin/workflows': typeof AuthenticatedAgentAdminWorkflowsRoute
  '/dispositif-workflow/$workflowId': typeof AuthenticatedAgentDispositifWorkflowWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/2fa': typeof R2faRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup-password': typeof SetupPasswordRoute
  '/_authenticated/_agent': typeof AuthenticatedAgentRouteWithChildren
  '/_authenticated/_benef': typeof AuthenticatedBenefRouteWithChildren
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_agent/cadre-resultat': typeof AuthenticatedAgentCadreResultatRoute
  '/_authenticated/_agent/dispositifs': typeof AuthenticatedAgentDispositifsRoute
  '/_authenticated/_agent/financements': typeof AuthenticatedAgentFinancementsRoute
  '/_authenticated/_agent/imputation': typeof AuthenticatedAgentImputationRoute
  '/_authenticated/_agent/indicateurs': typeof AuthenticatedAgentIndicateursRoute
  '/_authenticated/_agent/jeunes': typeof AuthenticatedAgentJeunesRoute
  '/_authenticated/_agent/pf-espace': typeof AuthenticatedAgentPfEspaceRoute
  '/_authenticated/_agent/plans-decaissement': typeof AuthenticatedAgentPlansDecaissementRoute
  '/_authenticated/_agent/projets': typeof AuthenticatedAgentProjetsRoute
  '/_authenticated/_agent/rapports': typeof AuthenticatedAgentRapportsRoute
  '/_authenticated/_agent/recouvrement': typeof AuthenticatedAgentRecouvrementRoute
  '/_authenticated/_agent/remboursements': typeof AuthenticatedAgentRemboursementsRoute
  '/_authenticated/_agent/suivi': typeof AuthenticatedAgentSuiviRoute
  '/_authenticated/_agent/transmission': typeof AuthenticatedAgentTransmissionRoute
  '/_authenticated/_benef/mes-pieces': typeof AuthenticatedBenefMesPiecesRoute
  '/_authenticated/_benef/mes-projets': typeof AuthenticatedBenefMesProjetsRoute
  '/_authenticated/_agent/admin/localites': typeof AuthenticatedAgentAdminLocalitesRoute
  '/_authenticated/_agent/admin/parametres': typeof AuthenticatedAgentAdminParametresRoute
  '/_authenticated/_agent/admin/partenaires': typeof AuthenticatedAgentAdminPartenairesRoute
  '/_authenticated/_agent/admin/personnels': typeof AuthenticatedAgentAdminPersonnelsRoute
  '/_authenticated/_agent/admin/profils': typeof AuthenticatedAgentAdminProfilsRoute
  '/_authenticated/_agent/admin/referentiels': typeof AuthenticatedAgentAdminReferentielsRoute
  '/_authenticated/_agent/admin/unites': typeof AuthenticatedAgentAdminUnitesRoute
  '/_authenticated/_agent/admin/workflows': typeof AuthenticatedAgentAdminWorkflowsRoute
  '/_authenticated/_agent/dispositif-workflow/$workflowId': typeof AuthenticatedAgentDispositifWorkflowWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/2fa'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/compte'
    | '/dashboard'
    | '/cadre-resultat'
    | '/dispositifs'
    | '/financements'
    | '/imputation'
    | '/indicateurs'
    | '/jeunes'
    | '/pf-espace'
    | '/plans-decaissement'
    | '/projets'
    | '/rapports'
    | '/recouvrement'
    | '/remboursements'
    | '/suivi'
    | '/transmission'
    | '/mes-pieces'
    | '/mes-projets'
    | '/admin/localites'
    | '/admin/parametres'
    | '/admin/partenaires'
    | '/admin/personnels'
    | '/admin/profils'
    | '/admin/referentiels'
    | '/admin/unites'
    | '/admin/workflows'
    | '/dispositif-workflow/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/2fa'
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/'
    | '/compte'
    | '/dashboard'
    | '/cadre-resultat'
    | '/dispositifs'
    | '/financements'
    | '/imputation'
    | '/indicateurs'
    | '/jeunes'
    | '/pf-espace'
    | '/plans-decaissement'
    | '/projets'
    | '/rapports'
    | '/recouvrement'
    | '/remboursements'
    | '/suivi'
    | '/transmission'
    | '/mes-pieces'
    | '/mes-projets'
    | '/admin/localites'
    | '/admin/parametres'
    | '/admin/partenaires'
    | '/admin/personnels'
    | '/admin/profils'
    | '/admin/referentiels'
    | '/admin/unites'
    | '/admin/workflows'
    | '/dispositif-workflow/$workflowId'
  id:
    | '__root__'
    | '/2fa'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/setup-password'
    | '/_authenticated/_agent'
    | '/_authenticated/_benef'
    | '/_authenticated/compte'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/_authenticated/_agent/cadre-resultat'
    | '/_authenticated/_agent/dispositifs'
    | '/_authenticated/_agent/financements'
    | '/_authenticated/_agent/imputation'
    | '/_authenticated/_agent/indicateurs'
    | '/_authenticated/_agent/jeunes'
    | '/_authenticated/_agent/pf-espace'
    | '/_authenticated/_agent/plans-decaissement'
    | '/_authenticated/_agent/projets'
    | '/_authenticated/_agent/rapports'
    | '/_authenticated/_agent/recouvrement'
    | '/_authenticated/_agent/remboursements'
    | '/_authenticated/_agent/suivi'
    | '/_authenticated/_agent/transmission'
    | '/_authenticated/_benef/mes-pieces'
    | '/_authenticated/_benef/mes-projets'
    | '/_authenticated/_agent/admin/localites'
    | '/_authenticated/_agent/admin/parametres'
    | '/_authenticated/_agent/admin/partenaires'
    | '/_authenticated/_agent/admin/personnels'
    | '/_authenticated/_agent/admin/profils'
    | '/_authenticated/_agent/admin/referentiels'
    | '/_authenticated/_agent/admin/unites'
    | '/_authenticated/_agent/admin/workflows'
    | '/_authenticated/_agent/dispositif-workflow/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R2faRoute: typeof R2faRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/2fa': {
      id: '/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof R2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_agent': {
      id: '/_authenticated/_agent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_benef': {
      id: '/_authenticated/_benef'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedBenefRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_agent/cadre-resultat': {
      id: '/_authenticated/_agent/cadre-resultat'
      path: '/cadre-resultat'
      fullPath: '/cadre-resultat'
      preLoaderRoute: typeof AuthenticatedAgentCadreResultatRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/dispositifs': {
      id: '/_authenticated/_agent/dispositifs'
      path: '/dispositifs'
      fullPath: '/dispositifs'
      preLoaderRoute: typeof AuthenticatedAgentDispositifsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/financements': {
      id: '/_authenticated/_agent/financements'
      path: '/financements'
      fullPath: '/financements'
      preLoaderRoute: typeof AuthenticatedAgentFinancementsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/imputation': {
      id: '/_authenticated/_agent/imputation'
      path: '/imputation'
      fullPath: '/imputation'
      preLoaderRoute: typeof AuthenticatedAgentImputationRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/indicateurs': {
      id: '/_authenticated/_agent/indicateurs'
      path: '/indicateurs'
      fullPath: '/indicateurs'
      preLoaderRoute: typeof AuthenticatedAgentIndicateursRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/jeunes': {
      id: '/_authenticated/_agent/jeunes'
      path: '/jeunes'
      fullPath: '/jeunes'
      preLoaderRoute: typeof AuthenticatedAgentJeunesRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/pf-espace': {
      id: '/_authenticated/_agent/pf-espace'
      path: '/pf-espace'
      fullPath: '/pf-espace'
      preLoaderRoute: typeof AuthenticatedAgentPfEspaceRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/plans-decaissement': {
      id: '/_authenticated/_agent/plans-decaissement'
      path: '/plans-decaissement'
      fullPath: '/plans-decaissement'
      preLoaderRoute: typeof AuthenticatedAgentPlansDecaissementRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/projets': {
      id: '/_authenticated/_agent/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedAgentProjetsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/rapports': {
      id: '/_authenticated/_agent/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedAgentRapportsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/recouvrement': {
      id: '/_authenticated/_agent/recouvrement'
      path: '/recouvrement'
      fullPath: '/recouvrement'
      preLoaderRoute: typeof AuthenticatedAgentRecouvrementRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/remboursements': {
      id: '/_authenticated/_agent/remboursements'
      path: '/remboursements'
      fullPath: '/remboursements'
      preLoaderRoute: typeof AuthenticatedAgentRemboursementsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/suivi': {
      id: '/_authenticated/_agent/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof AuthenticatedAgentSuiviRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/transmission': {
      id: '/_authenticated/_agent/transmission'
      path: '/transmission'
      fullPath: '/transmission'
      preLoaderRoute: typeof AuthenticatedAgentTransmissionRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_benef/mes-pieces': {
      id: '/_authenticated/_benef/mes-pieces'
      path: '/mes-pieces'
      fullPath: '/mes-pieces'
      preLoaderRoute: typeof AuthenticatedBenefMesPiecesRouteImport
      parentRoute: typeof AuthenticatedBenefRoute
    }
    '/_authenticated/_benef/mes-projets': {
      id: '/_authenticated/_benef/mes-projets'
      path: '/mes-projets'
      fullPath: '/mes-projets'
      preLoaderRoute: typeof AuthenticatedBenefMesProjetsRouteImport
      parentRoute: typeof AuthenticatedBenefRoute
    }
    '/_authenticated/_agent/admin/localites': {
      id: '/_authenticated/_agent/admin/localites'
      path: '/admin/localites'
      fullPath: '/admin/localites'
      preLoaderRoute: typeof AuthenticatedAgentAdminLocalitesRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/parametres': {
      id: '/_authenticated/_agent/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAgentAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/partenaires': {
      id: '/_authenticated/_agent/admin/partenaires'
      path: '/admin/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AuthenticatedAgentAdminPartenairesRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/personnels': {
      id: '/_authenticated/_agent/admin/personnels'
      path: '/admin/personnels'
      fullPath: '/admin/personnels'
      preLoaderRoute: typeof AuthenticatedAgentAdminPersonnelsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/profils': {
      id: '/_authenticated/_agent/admin/profils'
      path: '/admin/profils'
      fullPath: '/admin/profils'
      preLoaderRoute: typeof AuthenticatedAgentAdminProfilsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/referentiels': {
      id: '/_authenticated/_agent/admin/referentiels'
      path: '/admin/referentiels'
      fullPath: '/admin/referentiels'
      preLoaderRoute: typeof AuthenticatedAgentAdminReferentielsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/unites': {
      id: '/_authenticated/_agent/admin/unites'
      path: '/admin/unites'
      fullPath: '/admin/unites'
      preLoaderRoute: typeof AuthenticatedAgentAdminUnitesRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/admin/workflows': {
      id: '/_authenticated/_agent/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAgentAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_agent/dispositif-workflow/$workflowId': {
      id: '/_authenticated/_agent/dispositif-workflow/$workflowId'
      path: '/dispositif-workflow/$workflowId'
      fullPath: '/dispositif-workflow/$workflowId'
      preLoaderRoute: typeof AuthenticatedAgentDispositifWorkflowWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
  }
}

interface AuthenticatedAgentRouteChildren {
  AuthenticatedAgentCadreResultatRoute: typeof AuthenticatedAgentCadreResultatRoute
  AuthenticatedAgentDispositifsRoute: typeof AuthenticatedAgentDispositifsRoute
  AuthenticatedAgentFinancementsRoute: typeof AuthenticatedAgentFinancementsRoute
  AuthenticatedAgentImputationRoute: typeof AuthenticatedAgentImputationRoute
  AuthenticatedAgentIndicateursRoute: typeof AuthenticatedAgentIndicateursRoute
  AuthenticatedAgentJeunesRoute: typeof AuthenticatedAgentJeunesRoute
  AuthenticatedAgentPfEspaceRoute: typeof AuthenticatedAgentPfEspaceRoute
  AuthenticatedAgentPlansDecaissementRoute: typeof AuthenticatedAgentPlansDecaissementRoute
  AuthenticatedAgentProjetsRoute: typeof AuthenticatedAgentProjetsRoute
  AuthenticatedAgentRapportsRoute: typeof AuthenticatedAgentRapportsRoute
  AuthenticatedAgentRecouvrementRoute: typeof AuthenticatedAgentRecouvrementRoute
  AuthenticatedAgentRemboursementsRoute: typeof AuthenticatedAgentRemboursementsRoute
  AuthenticatedAgentSuiviRoute: typeof AuthenticatedAgentSuiviRoute
  AuthenticatedAgentTransmissionRoute: typeof AuthenticatedAgentTransmissionRoute
  AuthenticatedAgentAdminLocalitesRoute: typeof AuthenticatedAgentAdminLocalitesRoute
  AuthenticatedAgentAdminParametresRoute: typeof AuthenticatedAgentAdminParametresRoute
  AuthenticatedAgentAdminPartenairesRoute: typeof AuthenticatedAgentAdminPartenairesRoute
  AuthenticatedAgentAdminPersonnelsRoute: typeof AuthenticatedAgentAdminPersonnelsRoute
  AuthenticatedAgentAdminProfilsRoute: typeof AuthenticatedAgentAdminProfilsRoute
  AuthenticatedAgentAdminReferentielsRoute: typeof AuthenticatedAgentAdminReferentielsRoute
  AuthenticatedAgentAdminUnitesRoute: typeof AuthenticatedAgentAdminUnitesRoute
  AuthenticatedAgentAdminWorkflowsRoute: typeof AuthenticatedAgentAdminWorkflowsRoute
  AuthenticatedAgentDispositifWorkflowWorkflowIdRoute: typeof AuthenticatedAgentDispositifWorkflowWorkflowIdRoute
}

const AuthenticatedAgentRouteChildren: AuthenticatedAgentRouteChildren = {
  AuthenticatedAgentCadreResultatRoute: AuthenticatedAgentCadreResultatRoute,
  AuthenticatedAgentDispositifsRoute: AuthenticatedAgentDispositifsRoute,
  AuthenticatedAgentFinancementsRoute: AuthenticatedAgentFinancementsRoute,
  AuthenticatedAgentImputationRoute: AuthenticatedAgentImputationRoute,
  AuthenticatedAgentIndicateursRoute: AuthenticatedAgentIndicateursRoute,
  AuthenticatedAgentJeunesRoute: AuthenticatedAgentJeunesRoute,
  AuthenticatedAgentPfEspaceRoute: AuthenticatedAgentPfEspaceRoute,
  AuthenticatedAgentPlansDecaissementRoute:
    AuthenticatedAgentPlansDecaissementRoute,
  AuthenticatedAgentProjetsRoute: AuthenticatedAgentProjetsRoute,
  AuthenticatedAgentRapportsRoute: AuthenticatedAgentRapportsRoute,
  AuthenticatedAgentRecouvrementRoute: AuthenticatedAgentRecouvrementRoute,
  AuthenticatedAgentRemboursementsRoute: AuthenticatedAgentRemboursementsRoute,
  AuthenticatedAgentSuiviRoute: AuthenticatedAgentSuiviRoute,
  AuthenticatedAgentTransmissionRoute: AuthenticatedAgentTransmissionRoute,
  AuthenticatedAgentAdminLocalitesRoute: AuthenticatedAgentAdminLocalitesRoute,
  AuthenticatedAgentAdminParametresRoute:
    AuthenticatedAgentAdminParametresRoute,
  AuthenticatedAgentAdminPartenairesRoute:
    AuthenticatedAgentAdminPartenairesRoute,
  AuthenticatedAgentAdminPersonnelsRoute:
    AuthenticatedAgentAdminPersonnelsRoute,
  AuthenticatedAgentAdminProfilsRoute: AuthenticatedAgentAdminProfilsRoute,
  AuthenticatedAgentAdminReferentielsRoute:
    AuthenticatedAgentAdminReferentielsRoute,
  AuthenticatedAgentAdminUnitesRoute: AuthenticatedAgentAdminUnitesRoute,
  AuthenticatedAgentAdminWorkflowsRoute: AuthenticatedAgentAdminWorkflowsRoute,
  AuthenticatedAgentDispositifWorkflowWorkflowIdRoute:
    AuthenticatedAgentDispositifWorkflowWorkflowIdRoute,
}

const AuthenticatedAgentRouteWithChildren =
  AuthenticatedAgentRoute._addFileChildren(AuthenticatedAgentRouteChildren)

interface AuthenticatedBenefRouteChildren {
  AuthenticatedBenefMesPiecesRoute: typeof AuthenticatedBenefMesPiecesRoute
  AuthenticatedBenefMesProjetsRoute: typeof AuthenticatedBenefMesProjetsRoute
}

const AuthenticatedBenefRouteChildren: AuthenticatedBenefRouteChildren = {
  AuthenticatedBenefMesPiecesRoute: AuthenticatedBenefMesPiecesRoute,
  AuthenticatedBenefMesProjetsRoute: AuthenticatedBenefMesProjetsRoute,
}

const AuthenticatedBenefRouteWithChildren =
  AuthenticatedBenefRoute._addFileChildren(AuthenticatedBenefRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRouteWithChildren
  AuthenticatedBenefRoute: typeof AuthenticatedBenefRouteWithChildren
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRouteWithChildren,
  AuthenticatedBenefRoute: AuthenticatedBenefRouteWithChildren,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R2faRoute: R2faRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
